// @ts-nocheck
function money(value) { return `Rs ${(Number(value) || 0).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`; }
function date(value) { return value ? new Date(value).toLocaleDateString("en-IN") : "-"; }

export default function TripHistory({ trips }) {
  if (!trips.length) return <p className="empty">No trips recorded yet.</p>;
  return <div className="entry-list">{trips.map((trip) => {
    const diesel = trip.dieselFills || [];
    const rto = trip.rtoEntries || [];
    const other = trip.otherExpenses || [];
    return <details className="entry" key={trip._id}><summary><span><strong>{trip.driverId?.name || "No driver recorded"}</strong><br /><small>{trip.loadingLocation}{trip.unloadingLocation ? ` to ${trip.unloadingLocation}` : " · In progress"} · {date(trip.createdAt)}</small></span><span className={`status ${trip.status === "open" ? "status-open" : "status-closed"}`}>{trip.status}</span></summary><div className="trip-history-detail"><div><span className="stat-label">Advance</span><strong>{money(trip.driverAdvance?.amount)}</strong><small>{date(trip.driverAdvance?.date)}</small></div><div><span className="stat-label">Loading expense</span><strong>{money(trip.loadingExpense)}</strong></div><div><span className="stat-label">Unloading expense</span><strong>{money(trip.unloadingExpense)}</strong></div><div><span className="stat-label">KM / mileage</span><strong>{trip.settlement?.totalKm ?? "-"}</strong><small>{trip.settlement?.mileage ? `${trip.settlement.mileage} km/L` : "Pending closure"}</small></div><div><span className="stat-label">Diesel total</span><strong>{money(trip.settlement?.totalDieselValue || diesel.reduce((sum, fill) => sum + Number(fill.value || 0), 0))}</strong><small>{trip.settlement?.totalDieselLitres ?? diesel.reduce((sum, fill) => sum + Number(fill.volume || 0), 0)} L</small></div><div><span className="stat-label">Settlement balance</span><strong>{trip.settlement ? money(trip.settlement.balance) : "Open"}</strong></div><div className="field-full"><span className="stat-label">Diesel fills</span>{diesel.length ? diesel.map((fill, index) => <small key={`${trip._id}-diesel-${index}`}>#{index + 1}: {fill.volume} L × {money(fill.rate)} = {money(fill.value)} · KM {fill.odometerKm ?? "-"} · {date(fill.date)}<br /></small>) : <small>None</small>}</div><div className="field-full"><span className="stat-label">RTO entries</span>{rto.length ? rto.map((entry, index) => <small key={`${trip._id}-rto-${index}`}>#{index + 1}: {money(entry.amount)} · {date(entry.date)}<br /></small>) : <small>None</small>}</div><div className="field-full"><span className="stat-label">Other expenses</span>{other.length ? other.map((entry, index) => <small key={`${trip._id}-other-${index}`}>#{index + 1}: {money(entry.amount)} · {entry.note || "No note"} · {date(entry.date)}<br /></small>) : <small>None</small>}</div></div></details>;
  })}</div>;
}
